Звдвние 6: добавленна функциональность регистрации пользователя
gpb-it-factory/davydova-middle-service pull request #4
Opened 2024-06-02 13:47 UTC by alina-gasprom

2024-06-02 13:54 UTC, alina-gasprom commented
Я в контроллере попыталась реализовать стртегию, как рассказывал Костя, всегда отдавать код 200

2024-06-04 11:02 UTC, konstantin-kozlovskiy requested changes
Нужны ответы на вопросы ) и мелкие правки

2024-06-04 11:02 UTC, konstantin-kozlovskiy commented on src/main/java/ru/gpbf/middle/entity/ErrorEntity.java
> +    private UUID trace_id;
почему появился snake_case ?

2024-06-04 11:02 UTC, konstantin-kozlovskiy commented on src/main/java/ru/gpbf/middle/exception/ABSRequestError.java
> +    private UUID trace_id;
еще snake_case

2024-06-04 11:02 UTC, konstantin-kozlovskiy commented on src/main/java/ru/gpbf/middle/web/client/UserWebClient.java
> +                }).blockOptional();
сомнительное решение, использовать реактивный веб клиент и ставить блок, почему так?)

2024-06-04 11:02 UTC, konstantin-kozlovskiy commented on src/test/java/ru/gpbf/middle/web/client/UserWebClientTest.java
> +    //шнасов что null туда попадет сейчас нет, проверка на всякий случай
опечатка

2024-06-05 11:11 UTC, alina-gasprom commented on src/main/java/ru/gpbf/middle/web/client/UserWebClient.java
> +                }).blockOptional();
После вчерашний лекции вопрос уже реторический) Но и до лекции добрые люди на stackoverflow рассказали, что нет смысла использовать инструмент придуманный для ассинхроного взаимодействия в синхронном коде. Хотя вопрос зачем тогда у них в api есть блокирующие методы для меня остается открытым)

2024-06-05 11:12 UTC, alina-gasprom commented on src/main/java/ru/gpbf/middle/entity/ErrorEntity.java
> +    private UUID trace_id;
Это не мое, мне кто то подкинул))

2024-06-05 11:14 UTC, alina-gasprom commented on src/test/java/ru/gpbf/middle/web/client/UserWebClientTest.java
> +    //шнасов что null туда попадет сейчас нет, проверка на всякий случай
А концепции код 200 на все првально реализованна? И у меня остается теперь вопрос как это правильно в спеке описать что бы человеку на другой стороне было понятно

2024-06-05 11:15 UTC, alina-gasprom commented on src/test/java/ru/gpbf/middle/web/client/UserWebClientTest.java
> +    //шнасов что null туда попадет сейчас нет, проверка на всякий случай
А концепция код 200 на все правильно реализованна? И у меня остается теперь вопрос как это правильно в спеке описать что бы человеку на другой стороне было понятно

2024-06-12 19:23 UTC, alina-gasprom commented on src/test/java/ru/gpbf/middle/web/client/UserWebClientTest.java
> +    //шнасов что null туда попадет сейчас нет, проверка на всякий случай
Меня в первую очередь смущает что любая не предвиденная ошибка и код уже не будет 200(решение вижу два - помещать внутри контроллера все в try catch, что очень не приятно выглядит или ловить все в @ControllerAdvice), и еще хочется прям какой то флаг повесить что бы сразу понятно было сакссес или не сакссес, но куда его повесить? отдавть массив объектов, где первый объект будет тру или фолс? или это излишне? Но если это излишне то дессерилизовать не удобно т.к. может прийти два разных объекта в зависмисости от того успешно прошел запрос или нет 

И я еще не сделал проверку на то зарегестрирован ли пользовтель или нет, потому что в моей голове была логика что бек будет отдавать описание ошибки и я ее уже буду обрабатывать как мне нужно, но сейчас мне кажется что это какая то не правильная логика, построенная на догадках и вообще так не удобно и лучше бы два запроса отпарвлять на бек (на проверку не зарегестриоован ли и в случае если не зарегестрирован регистрировать)

2024-06-12 19:23 UTC, alina-gasprom commented on src/test/java/ru/gpbf/middle/web/client/UserWebClientTest.java
> +    //шнасов что null туда попадет сейчас нет, проверка на всякий случай
сорри за лонгрид

2024-06-13 08:49 UTC, konstantin-kozlovskiy approved these changes

2024-06-13 08:50 UTC, konstantin-kozlovskiy commented on src/test/java/ru/gpbf/middle/web/client/UserWebClientTest.java
> +    //шнасов что null туда попадет сейчас нет, проверка на всякий случай
> А концепция код 200 на все правильно реализована? 
в коде вижу и 400 код и 204, не совсем понимаю откуда тут концепция код 200 на все )

2024-06-13 11:09 UTC, merged