Задание 7: добавленна функциональность создания счёта
gpb-it-factory/davydova-middle-service pull request #8
Opened 2024-06-17 21:48 UTC by alina-gasprom

2024-06-25 17:19 UTC, vaganov-vadim requested changes
Привет! Хорошая работа! Добавил комментов по возможным местам улучшений.

2024-06-25 17:19 UTC, vaganov-vadim commented on src/main/java/ru/gpbf/middle/web/client/AccountWebClient.java
> +        URI uri = URI.create(environment.getProperty("abs.url") + environment.getProperty("abs.path.register") + "/" + accountRegister.getUserTelegramId() + environment.getProperty("abs.path.account"
Лучше использовать не Environment, а configuration properties - https://www.baeldung.com/configuration-properties-in-spring-boot

2024-06-25 17:19 UTC, vaganov-vadim commented on src/main/java/ru/gpbf/middle/web/client/AccountWebClient.java
> +    public Optional<ErrorEntity> register(AccountRegister accountRegister) {
Не уверен, что здесь Optional хорошо заходит, особенно с учётом того, что мы выкидываем исключения. Тут скорее логика - успешно (void) или исключение. Третьего как будто не дано.

2024-06-25 17:19 UTC, vaganov-vadim commented on src/main/java/ru/gpbf/middle/application/gateway/AccountGatewayImpl.java
> +    public Optional<ABSRequestError> register(AccountRegister accountRegister) {
Тоже не уверен про Optional, хотя тут немного логичнее, но это не самое конвенциальное его применение) Возможно, проще сделать отдельную абстракцию или всё же прокинуть исключение. Если хочется более функционального подхода, то приходи в личку.

2024-06-25 17:19 UTC, vaganov-vadim commented on src/main/java/ru/gpbf/middle/application/gateway/AccountGatewayImpl.java
> +        if (response.isPresent()) {
В данном случае можно использовать .map на Optional, так будет удачнее и лишний if уйдёт.

2024-06-25 17:19 UTC, vaganov-vadim commented on src/test/java/ru/gpbf/middle/WebClientData.java
> +    public static final String ACCOUNT_REGISTER = "{\"message\":\"account was not registered\",\"type\":\"Bad request\",\"code\":\"400\",\"traceId\":\"4d8656de-1781-498a-97ed-39d9f719dbb8\"}";
В идеале такие штуки лучше выносить в ресурсы в отдельные json-файлы, так проще их поддерживать.

2024-06-27 11:01 UTC, alina-gasprom commented on src/main/java/ru/gpbf/middle/web/client/AccountWebClient.java
> +        URI uri = URI.create(environment.getProperty("abs.url") + environment.getProperty("abs.path.register") + "/" + accountRegister.getUserTelegramId() + environment.getProperty("abs.path.account"
Сделанно)

2024-06-27 11:05 UTC, alina-gasprom commented on src/main/java/ru/gpbf/middle/application/gateway/AccountGatewayImpl.java
> +    public Optional<ABSRequestError> register(AccountRegister accountRegister) {
Это была попытка повторить за Максимом, но так как в java нет Result использовала Optional(больше так не буду) Много изменений получилось потому что в фиче создания пользователей использовалась такая же логика, там тоже поменяла на выбрасывание исключения.

По более функциональному подходу это Result в java руками создать(видела такие примеры)?

2024-06-27 11:06 UTC, alina-gasprom commented on src/test/java/ru/gpbf/middle/WebClientData.java
> +    public static final String ACCOUNT_REGISTER = "{\"message\":\"account was not registered\",\"type\":\"Bad request\",\"code\":\"400\",\"traceId\":\"4d8656de-1781-498a-97ed-39d9f719dbb8\"}";
конкретно этот класс удалила, json вынесла в файлы

2024-06-29 10:09 UTC, vaganov-vadim approved these changes
Бонус - можно RestTemplate заменить на RestClient, это более современный клиент.

2024-06-30 10:46 UTC, merged